name: Comprobar tokens

on:
  push:

jobs:
  comprobar-dev-token:
    runs-on: [self-hosted, Windows, X64]

    steps:
      - name: Comparar DEV_TOKEN
        shell: powershell
        env:
          DEV_TOKEN: ${{ secrets.DEV_TOKEN }}
        run: |
          if ($env:DEV_TOKEN -eq $env:LOCAL_DEV_TOKEN) {
            Write-Host "CORRECTO: los tokens coinciden."
          } else {
            Write-Error "ERROR: los tokens no coinciden."
            exit 1
          }
